/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-12 18:14:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class books_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1773287252733L));
    _jspx_dependants.put("jar:file:/D:/LapTrinhWeb/QUAN_LY_THU_VIEN/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LibraryManagement/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>Thư Viện Pro - Quản Lý Sách</title>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/datatables/dataTables.bootstrap4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\r\n");
      out.write("                        <h1 class=\"h3 mb-0 text-gray-800\">Quản Lý Sách</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"mb-4 row\">\r\n");
      out.write("					    <div class=\"col-md-6\">\r\n");
      out.write("					        <a href=\"#addBookModal\" class=\"btn btn-primary btn-icon-split\" data-toggle=\"modal\">\r\n");
      out.write("					            <span class=\"icon text-white-50\"><i class=\"fas fa-plus\"></i></span>\r\n");
      out.write("					            <span class=\"text\">Thêm sách mới</span>\r\n");
      out.write("					        </a>\r\n");
      out.write("					    </div>\r\n");
      out.write("					   \r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card shadow mb-4\">\r\n");
      out.write("                        <div class=\"card-header py-3\">\r\n");
      out.write("                            <h6 class=\"m-0 font-weight-bold text-primary\">Danh sách đầu sách trong kho</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <div class=\"table-responsive\">\r\n");
      out.write("                                <table class=\"table table-bordered\" id=\"dataTable\" width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>Mã số</th>\r\n");
      out.write("                                            <th>Ảnh</th>\r\n");
      out.write("                                            <th>Tên sách</th>\r\n");
      out.write("                                            <th>Tác giả</th>\r\n");
      out.write("                                            <th>Thể loại</th>\r\n");
      out.write("                                            <th>Số lượng</th>\r\n");
      out.write("                                            <th>Thao tác</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("									    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("									</tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   <div id=\"addBookModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content border-0 shadow-lg\">\r\n");
      out.write("            <form action=\"add\" method=\"post\">\r\n");
      out.write("                <div class=\"modal-header bg-primary text-white\">						\r\n");
      out.write("                    <h5 class=\"modal-title font-weight-bold\">\r\n");
      out.write("                        <i class=\"fas fa-book-medical mr-2\"></i>Thêm Sách Mới\r\n");
      out.write("                    </h5>\r\n");
      out.write("                    <button type=\"button\" class=\"close text-white\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body p-4\">					\r\n");
      out.write("                    <div class=\"form-group mb-3\">\r\n");
      out.write("                        <label class=\"small font-weight-bold text-dark\">Tên sách</label>\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <div class=\"input-group-prepend\">\r\n");
      out.write("                                <span class=\"input-group-text bg-light border-right-0\"><i class=\"fas fa-bookmark text-primary\"></i></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input name=\"title\" type=\"text\" class=\"form-control border-left-0\" placeholder=\"Nhập tên sách...\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6 form-group mb-3\">\r\n");
      out.write("                            <label class=\"small font-weight-bold text-dark\">Tác giả</label>\r\n");
      out.write("                            <input name=\"author\" type=\"text\" class=\"form-control\" placeholder=\"Tên tác giả\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 form-group mb-3\">\r\n");
      out.write("						    <label class=\"small font-weight-bold text-dark\">Thể loại</label>\r\n");
      out.write("						    <select name=\"category\" class=\"form-control\" required>\r\n");
      out.write("						        <option value=\"\" selected disabled>Chọn thể loại</option>\r\n");
      out.write("						        <optgroup label=\"Khoa học & Công nghệ\">\r\n");
      out.write("						            <option value=\"Công nghệ thông tin\">Công nghệ thông tin</option>\r\n");
      out.write("						            <option value=\"Khoa học tự nhiên\">Khoa học tự nhiên</option>\r\n");
      out.write("						            <option value=\"Trí tuệ nhân tạo\">Trí tuệ nhân tạo</option>\r\n");
      out.write("						        </optgroup>\r\n");
      out.write("						        <optgroup label=\"Kinh tế & Kỹ năng\">\r\n");
      out.write("						            <option value=\"Kinh tế - Tài chính\">Kinh tế - Tài chính</option>\r\n");
      out.write("						            <option value=\"Quản trị kinh doanh\">Quản trị kinh doanh</option>\r\n");
      out.write("						            <option value=\"Kỹ năng sống (Self-help)\">Kỹ năng sống (Self-help)</option>\r\n");
      out.write("						        </optgroup>\r\n");
      out.write("						        <optgroup label=\"Văn hóa - Nghệ thuật\">\r\n");
      out.write("						            <option value=\"Văn học trong nước\">Văn học trong nước</option>\r\n");
      out.write("						            <option value=\"Văn học nước ngoài\">Văn học nước ngoài</option>\r\n");
      out.write("						            <option value=\"Lịch sử - Triết học\">Lịch sử - Triết học</option>\r\n");
      out.write("						            <option value=\"Nghệ thuật - Hội họa\">Nghệ thuật - Hội họa</option>\r\n");
      out.write("						        </optgroup>\r\n");
      out.write("						        <optgroup label=\"Khác\">\r\n");
      out.write("						            <option value=\"Ngoại ngữ\">Ngoại ngữ</option>\r\n");
      out.write("						            <option value=\"Tạp chí / Truyện tranh\">Tạp chí / Truyện tranh</option>\r\n");
      out.write("						            <option value=\"Sách giáo khoa\">Sách giáo khoa</option>\r\n");
      out.write("						        </optgroup>\r\n");
      out.write("						    </select>\r\n");
      out.write("						</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group mb-0\">\r\n");
      out.write("                        <label class=\"small font-weight-bold text-dark\">Số lượng nhập kho</label>\r\n");
      out.write("                        <input name=\"quantity\" type=\"number\" class=\"form-control\" min=\"1\" value=\"1\" required>\r\n");
      out.write("                    </div>	\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group mb-3\">\r\n");
      out.write("					    <label class=\"small font-weight-bold text-dark\">Link ảnh bìa sách (URL)</label>\r\n");
      out.write("					    <div class=\"input-group\">\r\n");
      out.write("					        <div class=\"input-group-prepend\">\r\n");
      out.write("					            <span class=\"input-group-text\"><i class=\"fas fa-image text-primary\"></i></span>\r\n");
      out.write("					        </div>\r\n");
      out.write("					        <input name=\"image\" type=\"text\" class=\"form-control\" placeholder=\"Dán link ảnh từ internet vào đây...\">\r\n");
      out.write("					    </div>\r\n");
      out.write("					    <small class=\"text-muted\">Ví dụ: https://anhsach.com/bia-sach.jpg</small>\r\n");
      out.write("					</div>				\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer bg-light border-0\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary btn-sm px-4\" data-dismiss=\"modal\">Hủy bỏ</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary btn-sm px-4 shadow-sm\">\r\n");
      out.write("                        <i class=\"fas fa-check mr-1\"></i>Xác nhận thêm\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/datatables/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/datatables/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $('#dataTable').DataTable({\r\n");
      out.write("        	\r\n");
      out.write("            \"paging\": true,          // Bật phân trang (Phần số 1, 2, Tiếp)\r\n");
      out.write("            \"lengthChange\": true,    // Bật chọn số mục (Xem 10, 25, 50 mục)\r\n");
      out.write("            \"searching\": true,       // Bật ô tìm kiếm nội bộ (Lọc cực nhanh không cần Servlet)\r\n");
      out.write("            \"ordering\": true,        // Cho phép nhấn vào đầu cột để sắp xếp A-Z\r\n");
      out.write("            \"info\": true,            // Hiện dòng \"Đang xem 1 đến 7 trong tổng số 7 mục\"\r\n");
      out.write("            \"autoWidth\": false,\r\n");
      out.write("            \"responsive\": true,\r\n");
      out.write("            \"language\": {\r\n");
      out.write("                \"sProcessing\":   \"Đang xử lý...\",\r\n");
      out.write("                \"sLengthMenu\":   \"Xem _MENU_ mục\",\r\n");
      out.write("                \"sZeroRecords\":  \"Không tìm thấy dòng nào phù hợp\",\r\n");
      out.write("                \"sInfo\":         \"Đang xem _START_ đến _END_ trong tổng số _TOTAL_ mục\",\r\n");
      out.write("                \"sInfoEmpty\":    \"Đang xem 0 đến 0 trong tổng số 0 mục\",\r\n");
      out.write("                \"sInfoFiltered\": \"(được lọc từ _MAX_ mục)\",\r\n");
      out.write("                \"sSearch\":       \"Tìm kiếm:\",\r\n");
      out.write("                \"oPaginate\": {\r\n");
      out.write("                    \"sFirst\":    \"Đầu\",\r\n");
      out.write("                    \"sPrevious\": \"Trước\",\r\n");
      out.write("                    \"sNext\":     \"Tiếp\",\r\n");
      out.write("                    \"sLast\":     \"Cuối\"\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /books-list.jsp(58,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/books-list.jsp(58,13) '${listB}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listB}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /books-list.jsp(58,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("									        <tr>\r\n");
            out.write("									            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("									            <td>\r\n");
            out.write("												    <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"width: 45px; height: 60px; object-fit: cover;\" \r\n");
            out.write("												         class=\"shadow-sm rounded border\" \r\n");
            out.write("												         onerror=\"this.src='https://via.placeholder.com/45x60?text=No+Img'\">\r\n");
            out.write("												</td>\r\n");
            out.write("									            <td><a href=\"detail?bid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("									            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("									            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("									            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("									            <td>\r\n");
            out.write("									                <a href=\"loadBook?bid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-info btn-sm\">Sửa</a>\r\n");
            out.write("									                <a href=\"delete?bid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-danger btn-sm\">Xóa</a>\r\n");
            out.write("									            </td>\r\n");
            out.write("									        </tr>\r\n");
            out.write("									    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
