/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-18 07:44:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1773287252733L));
    _jspx_dependants.put("jar:file:/D:/LapTrinhWeb/LibraryManagement/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LibraryManagement/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Thư Viện Pro - Quản Lý Sách</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/fontawesome-free/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/sb-admin-2.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/datatables/dataTables.bootstrap4.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("	<div id=\"wrapper\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("			<div id=\"content\">\r\n");
      out.write("				");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("					<h1 class=\"h3 mb-4 text-gray-800\">Chỉnh sửa thông tin sách</h1>\r\n");
      out.write("					<div class=\"card shadow mb-4\">\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/edit\"\r\n");
      out.write("								method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("								<input name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"hidden\">\r\n");
      out.write("\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label>Tên sách</label> <input name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("										type=\"text\" class=\"form-control\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label>Tác giả</label> <input name=\"author\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text\" class=\"form-control\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label>Thể loại</label> <select name=\"category\"\r\n");
      out.write("										class=\"form-control\" required>\r\n");
      out.write("										<option value=\"\" disabled>Chọn thể loại</option>\r\n");
      out.write("\r\n");
      out.write("										<optgroup label=\"Khoa học & Công nghệ\">\r\n");
      out.write("											<option value=\"Công nghệ thông tin\"\r\n");
      out.write("												");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.category == 'Công nghệ thông tin' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Công\r\n");
      out.write("												nghệ thông tin</option>\r\n");
      out.write("											<option value=\"Khoa học tự nhiên\"\r\n");
      out.write("												");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.category == 'Khoa học tự nhiên' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Khoa\r\n");
      out.write("												học tự nhiên</option>\r\n");
      out.write("											<option value=\"Trí tuệ nhân tạo\"\r\n");
      out.write("												");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.category == 'Trí tuệ nhân tạo' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Trí\r\n");
      out.write("												tuệ nhân tạo</option>\r\n");
      out.write("										</optgroup>\r\n");
      out.write("\r\n");
      out.write("										<optgroup label=\"Kinh tế & Kỹ năng\">\r\n");
      out.write("											<option value=\"Kinh tế - Tài chính\"\r\n");
      out.write("												");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.category == 'Kinh tế - Tài chính' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Kinh\r\n");
      out.write("												tế - Tài chính</option>\r\n");
      out.write("											<option value=\"Quản trị kinh doanh\"\r\n");
      out.write("												");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.category == 'Quản trị kinh doanh' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Quản\r\n");
      out.write("												trị kinh doanh</option>\r\n");
      out.write("											<option value=\"Kỹ năng sống (Self-help)\"\r\n");
      out.write("												");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.category == 'Kỹ năng sống (Self-help)' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Kỹ\r\n");
      out.write("												năng sống (Self-help)</option>\r\n");
      out.write("										</optgroup>\r\n");
      out.write("\r\n");
      out.write("										<optgroup label=\"Văn hóa - Nghệ thuật\">\r\n");
      out.write("											<option value=\"Văn học trong nước\"\r\n");
      out.write("												");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.category == 'Văn học trong nước' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Văn\r\n");
      out.write("												học trong nước</option>\r\n");
      out.write("											<option value=\"Văn học nước ngoài\"\r\n");
      out.write("												");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.category == 'Văn học nước ngoài' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Văn\r\n");
      out.write("												học nước ngoài</option>\r\n");
      out.write("											<option value=\"Lịch sử - Triết học\"\r\n");
      out.write("												");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.category == 'Lịch sử - Triết học' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Lịch\r\n");
      out.write("												sử - Triết học</option>\r\n");
      out.write("											<option value=\"Nghệ thuật - Hội họa\"\r\n");
      out.write("												");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.category == 'Nghệ thuật - Hội họa' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Nghệ\r\n");
      out.write("												thuật - Hội họa</option>\r\n");
      out.write("										</optgroup>\r\n");
      out.write("\r\n");
      out.write("										<optgroup label=\"Khác\">\r\n");
      out.write("											<option value=\"Ngoại ngữ\"\r\n");
      out.write("												");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.category == 'Ngoại ngữ' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Ngoại\r\n");
      out.write("												ngữ</option>\r\n");
      out.write("											<option value=\"Tạp chí / Truyện tranh\"\r\n");
      out.write("												");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.category == 'Tạp chí / Truyện tranh' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Tạp\r\n");
      out.write("												chí / Truyện tranh</option>\r\n");
      out.write("											<option value=\"Sách giáo khoa\"\r\n");
      out.write("												");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.category == 'Sách giáo khoa' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Sách\r\n");
      out.write("												giáo khoa</option>\r\n");
      out.write("										</optgroup>\r\n");
      out.write("									</select>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label>Số lượng</label> <input name=\"quantity\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"number\" class=\"form-control\"\r\n");
      out.write("										required>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group mb-3\">\r\n");
      out.write("									<label class=\"small font-weight-bold text-dark\">Hình\r\n");
      out.write("										ảnh bìa sách</label>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"mb-2\">\r\n");
      out.write("										<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("											style=\"width: 70px; height: 100px; object-fit: cover;\"\r\n");
      out.write("											class=\"img-thumbnail\"> <small\r\n");
      out.write("											class=\"text-muted d-block\">Ảnh hiện tại</small>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<ul class=\"nav nav-pills mb-2\" id=\"imageMethodTab\"\r\n");
      out.write("										role=\"tablist\">\r\n");
      out.write("										<li class=\"nav-item\"><a\r\n");
      out.write("											class=\"nav-link active py-1 px-3 small\" id=\"url-tab\"\r\n");
      out.write("											data-toggle=\"pill\" href=\"#urlInput\" role=\"tab\">Dán Link\r\n");
      out.write("												URL</a></li>\r\n");
      out.write("										<li class=\"nav-item\"><a class=\"nav-link py-1 px-3 small\"\r\n");
      out.write("											id=\"file-tab\" data-toggle=\"pill\" href=\"#fileInput\" role=\"tab\">Tải\r\n");
      out.write("												tệp từ máy</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"tab-content border p-2 rounded bg-light\">\r\n");
      out.write("										<div class=\"tab-pane fade show active\" id=\"urlInput\"\r\n");
      out.write("											role=\"tabpanel\">\r\n");
      out.write("											<input name=\"image_url\" type=\"text\" class=\"form-control\"\r\n");
      out.write("												value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("												placeholder=\"https://anhsach.com/bia-sach.jpg\">\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"tab-pane fade\" id=\"fileInput\" role=\"tabpanel\">\r\n");
      out.write("											<div class=\"custom-file\">\r\n");
      out.write("												<input name=\"image_file\" type=\"file\"\r\n");
      out.write("													class=\"custom-file-input\" id=\"customFile\" accept=\"image/*\">\r\n");
      out.write("												<label class=\"custom-file-label\" for=\"customFile\">Chọn\r\n");
      out.write("													ảnh mới...</label>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<button type=\"submit\" class=\"btn btn-primary\">Lưu thay\r\n");
      out.write("									đổi</button>\r\n");
      out.write("								<a href=\"books\" class=\"btn btn-secondary\">Hủy bỏ</a>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("						");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<script\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("				<script\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("				<script\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("				<script\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/datatables/jquery.dataTables.min.js\"></script>\r\n");
      out.write("				<script\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/datatables/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("				<script>\r\n");
      out.write("					$('.custom-file-input').on(\r\n");
      out.write("							'change',\r\n");
      out.write("							function() {\r\n");
      out.write("								var fileName = $(this).val().split('\\\\').pop();\r\n");
      out.write("								$(this).next('.custom-file-label').addClass(\r\n");
      out.write("										\"selected\").html(fileName);\r\n");
      out.write("							});\r\n");
      out.write("				</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
