/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-17 13:14:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class navbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav\r\n");
      out.write("	class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\r\n");
      out.write("	<button id=\"sidebarToggleTop\"\r\n");
      out.write("		class=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("		<i class=\"fa fa-bars\"></i>\r\n");
      out.write("	</button>\r\n");
      out.write("\r\n");
      out.write("	<form action=\"search-nav\" method=\"get\"\r\n");
      out.write("		class=\"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search\">\r\n");
      out.write("		<div class=\"input-group\">\r\n");
      out.write("			<input type=\"text\" name=\"txt\"\r\n");
      out.write("				class=\"form-control bg-light border-0 small\"\r\n");
      out.write("				placeholder=\"Tìm kiếm tên sách hoặc tác giả...\" aria-label=\"Search\"\r\n");
      out.write("				aria-describedby=\"basic-addon2\">\r\n");
      out.write("			<div class=\"input-group-append\">\r\n");
      out.write("				<button class=\"btn btn-primary\" type=\"submit\">\r\n");
      out.write("					<i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("		<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("			class=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\"\r\n");
      out.write("			role=\"button\" data-toggle=\"dropdown\"> <i\r\n");
      out.write("				class=\"fas fa-bell fa-fw\"></i> <span\r\n");
      out.write("				class=\"badge badge-danger badge-counter\">3+</span>\r\n");
      out.write("		</a>\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\">\r\n");
      out.write("				<h6 class=\"dropdown-header\">Trung tâm thông báo</h6>\r\n");
      out.write("				<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("					<div class=\"mr-3\">\r\n");
      out.write("						<div class=\"icon-circle bg-primary\">\r\n");
      out.write("							<i class=\"fas fa-file-alt text-white\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"small text-gray-500\">12/03/2026</div>\r\n");
      out.write("						<span class=\"font-weight-bold\">Báo cáo tháng mới đã sẵn\r\n");
      out.write("							sàng!</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</a> <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Xem\r\n");
      out.write("					tất cả thông báo</a>\r\n");
      out.write("			</div></li>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"topbar-divider d-none d-sm-block\"></div>\r\n");
      out.write("\r\n");
      out.write("		<li class=\"nav-item dropdown no-arrow\"><a\r\n");
      out.write("			class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\"\r\n");
      out.write("			role=\"button\" data-toggle=\"dropdown\"> <span\r\n");
      out.write("				class=\"mr-2 d-none d-lg-inline text-gray-600 small\">Quản trị\r\n");
      out.write("					viên</span> <img class=\"img-profile rounded-circle\"\r\n");
      out.write("				src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/undraw_profile.svg\">\r\n");
      out.write("		</a>\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\">\r\n");
      out.write("				<a class=\"dropdown-item\" href=\"#\"> <i\r\n");
      out.write("					class=\"fas fa-user fa-sm fa-fw mr-2 text-gray-400\"></i> Hồ sơ cá\r\n");
      out.write("					nhân\r\n");
      out.write("				</a> <a class=\"dropdown-item\" href=\"#\"> <i\r\n");
      out.write("					class=\"fas fa-cogs fa-sm fa-fw mr-2 text-gray-400\"></i> Cài đặt\r\n");
      out.write("				</a>\r\n");
      out.write("				<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\r\n");
      out.write("				<a class=\"dropdown-item\"\r\n");
      out.write("					href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp\"> <i\r\n");
      out.write("					class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("					Đăng xuất\r\n");
      out.write("				</a>\r\n");
      out.write("			</div></li>\r\n");
      out.write("\r\n");
      out.write("	</ul>\r\n");
      out.write("</nav>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
